SELECT
    A.AUTHOR_ID,
    A.AUTHOR_NAME,
    B.CATEGORY,
    SUM(S.SALES * B.PRICE) AS TOTAL_SALES
FROM
    BOOK AS B
    JOIN AUTHOR AS A
    ON B.AUTHOR_ID = A.AUTHOR_ID
    JOIN BOOK_SALES AS S
    ON B.BOOK_ID = S.BOOK_ID AND
    S.SALES_DATE LIKE '2022-01%'
GROUP BY
    1,
    2,
    3
ORDER BY
    1,
    3 DESC