WITH CTE AS (
    SELECT
        PRODUCT_ID,
        SUM(SALES_AMOUNT) AS SALES_AMOUNT
    FROM
        OFFLINE_SALE
    GROUP BY
        1
)

SELECT
    P.PRODUCT_CODE,
    P.PRICE * C.SALES_AMOUNT AS SALES
FROM
    PRODUCT AS P
    JOIN CTE AS C
    ON P.PRODUCT_ID = C.PRODUCT_ID
ORDER BY
    2 DESC,
    1