SELECT
    C.CAR_ID,
    C.CAR_TYPE,
    ROUND((C.DAILY_FEE * (100 - D.DISCOUNT_RATE) / 100), 0) * 30 AS FEE
FROM
    CAR_RENTAL_COMPANY_CAR AS C
    JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY AS H
    ON C.CAR_ID = H.CAR_ID AND
    C.CAR_TYPE IN (
        '세단',
        'SUV'
    )
    JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN AS D
    ON C.CAR_TYPE = D.CAR_TYPE AND
    D.DURATION_TYPE LIKE '30%' AND
    (C.DAILY_FEE * (100 - D.DISCOUNT_RATE) / 100) * 30 BETWEEN 500000 AND 2000000
GROUP BY
    C.CAR_ID
HAVING
    (MIN(H.START_DATE) > '2022-11-30' OR MAX(H.END_DATE) < '2022-11-01')
ORDER BY
    3 DESC,
    2,
    1 DESC