SELECT
    DISTINCT D.ID,
    D.EMAIL,
    D.FIRST_NAME,
    D.LAST_NAME
FROM
    DEVELOPERS AS D
    JOIN SKILLCODES AS S
    ON S.CATEGORY = 'Front End' AND
    D.SKILL_CODE & S.CODE = S.CODE
ORDER BY
    1