WITH CTE AS (
    SELECT
        CAR_ID
    FROM
        CAR_RENTAL_COMPANY_RENTAL_HISTORY
    WHERE
        START_DATE BETWEEN '2022-08-01' AND '2022-10-31'
    GROUP BY
        CAR_ID
    HAVING
        COUNT(CAR_ID) >= 5
)

SELECT
    MONTH(H.START_DATE) AS MONTH,
    H.CAR_ID,
    COUNT(H.CAR_ID) AS RECORDS
FROM
    CAR_RENTAL_COMPANY_RENTAL_HISTORY AS H
    JOIN CTE AS C
    ON H.CAR_ID = C.CAR_ID
WHERE
    H.START_DATE BETWEEN '2022-08-01' AND '2022-10-31'
GROUP BY
    1,
    2
ORDER BY
    1,
    2 DESC