WITH CTE AS (
    SELECT
        YEAR(DIFFERENTIATION_DATE) AS YEAR,
        MAX(SIZE_OF_COLONY) AS MAX_SIZE
    FROM
        ECOLI_DATA
    GROUP BY
        1
)

SELECT
    YEAR(E.DIFFERENTIATION_DATE) AS YEAR,
    (
        SELECT
            C.MAX_SIZE
        FROM
            CTE AS C
        WHERE
            YEAR(E.DIFFERENTIATION_DATE) = C.YEAR
    ) - E.SIZE_OF_COLONY AS YEAR_DEV,
    E.ID
FROM
    ECOLI_DATA AS E
ORDER BY
    1,
    2