WITH CTE AS (
    SELECT
        ID,
        FISH_TYPE,
        LENGTH,
        ROW_NUMBER() OVER (PARTITION BY FISH_TYPE ORDER BY LENGTH DESC) AS RN
    FROM
        FISH_INFO
)

SELECT
    C.ID,
    N.FISH_NAME,
    C.LENGTH
FROM
    CTE AS C
    JOIN FISH_NAME_INFO AS N
    ON C.FISH_TYPE = N.FISH_TYPE
WHERE
    RN = 1
ORDER BY
    1
    
    