WITH CTE AS (
    SELECT
        DEPT_ID,
        ROUND(AVG(SAL), 0) AS AVG_SAL
    FROM
        HR_EMPLOYEES
    GROUP BY
        1
)

SELECT
    D.DEPT_ID,
    D.DEPT_NAME_EN,
    C.AVG_SAL
FROM
    HR_DEPARTMENT AS D
    JOIN CTE AS C
    ON D.DEPT_ID = C.DEPT_ID
ORDER BY
    3 DESC