SELECT
    CASE
        WHEN GROUP_CONCAT(S.CATEGORY) LIKE '%FRONT END%' AND GROUP_CONCAT(S.NAME) LIKE '%PYTHON%' THEN 'A'
        WHEN GROUP_CONCAT(S.NAME) LIKE '%C#%' THEN 'B'
        WHEN GROUP_CONCAT(S.CATEGORY) LIKE '%FRONT END%' THEN 'C'
    END AS GRADE,
    D.ID,
    D.EMAIL
FROM
    DEVELOPERS AS D
    JOIN SKILLCODES AS S
    ON D.SKILL_CODE & S.CODE = S.CODE
GROUP BY
    2,
    3
HAVING
    GRADE IS NOT NULL
ORDER BY
    1,
    2